### ISSUE TITLE
第二步生成蒙版报错，提示找不到CUDA运行库路径，但系统有安装，并重装CUDA，CUDNN等偿试过。

### ISSUE THREAD

**Issue by DreamLoveBetty** [huchang47/AetherConverTools#10]
以下是后台报错信息：系统：win11，python:3.10.11,CUDA:11.8-12.2
False

===================================BUG REPORT===================================
C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

  warn(msg)
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.9.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\Scripts\transparent-background.exe\__main__.py", line 4, in <module>
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\transparent_background\__init__.py", line 1, in <module>
    from transparent_background.Remover import Remover, console
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\transparent_background\Remover.py", line 20, in <module>
    from transparent_background.InSPyReNet import InSPyReNet_SwinB
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\transparent_background\InSPyReNet.py", line 12, in <module>
    from transparent_background.modules.layers import *
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\transparent_background\modules\layers.py", line 8, in <module>
    from kornia.morphology import dilation, erosion
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\kornia\__init__.py", line 11, in <module>
    from . import augmentation, color, contrib, core, enhance, feature, io, losses, metrics, morphology, tracking, utils, x
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\kornia\x\__init__.py", line 2, in <module>
    from .trainer import Trainer
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\kornia\x\trainer.py", line 11, in <module>
    from accelerate import Accelerator
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\utils\__init__.py", line 131, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\utils\bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\H\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by huchang47** [comment]
两个可能性：
1.需要特定的Pytouch，而不是普通的CUDA，所以卸载原来的，运行组件安装，里面有
2.多个Pyhton环境导致的，工作流调用的标准的系统变量中的环境，如果你启动了其他的环境，导致组件缺失
