### ISSUE TITLE
系统找不到指定文件，组件都已经安装，求大佬指点

### ISSUE THREAD

**Issue by ankokucao** [huchang47/AetherConverTools#11]
========== 以太转绘工作流脚本 ==========

工作流即将开始，请确保当前目录下有视频文件，且文件名格式为：video.mp4
如果在运行中程序出现错误，极大可能是缺少组件和自动下载模型不成功
请安装组件和科学上网后再次尝试。还有问题，请加群792358210敲打作者

加速成功！使用的设备：CUDA
请输入想要输出的视频帧率（默认15）：
Traceback (most recent call last):
  File "E:\AI\AetherConverTools\bin\01_VideoFrameExtraction.py", line 43, in <module>
    subprocess.call([
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
请按任意键继续. . .

**Comment by xiaomochn** [comment]
遇到同问题了 有解吗

**Comment by xiaomochn** [comment]
解决了 把 自己的Python目录\Python311\Scripts\ 加到环境变量中

**Comment by ankokucao** [comment]
> 解决了 把 自己的Python目录\Python311\Scripts\ 加到环境变量中

为什么我加了环境变量还是不行，照样报错，系统变量和用户变量都加了。

**Comment by xys669** [comment]
老哥有办法了吗
