### ISSUE TITLE
蹲个大佬求助，选择蒙版生成算法报错的问题

### ISSUE THREAD

**Issue by MysteryManTK** [huchang47/AetherConverTools#12]
Traceback (most recent call last):
  File "E:\AI_Animation\AetherConverTools\AetherConverTools-1.11\AetherConverTools-1.11\bin\02_MaskCreation.py", line 75, in <module>
    subprocess.call(['transparent-background', '--source', frame_out_dir, '--dest', mask_out_dir, '--type', 'map'])
  File "E:\sd-webui-aki\sd-webui-aki-v4.4\sd-webui-aki-v4.4\python\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "E:\sd-webui-aki\sd-webui-aki-v4.4\sd-webui-aki-v4.4\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\sd-webui-aki\sd-webui-aki-v4.4\sd-webui-aki-v4.4\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by huchang47** [comment]
没有transparent-background组件，安装它
pip install transparent-background
或者运行00_双击安装必要组件.bat

**Comment by wcyy** [comment]
不管用，。。我双击运行安装组件，。直接给我闪退了，生成蒙版时。同样报错。你说的文件我放了。没起作用

**Comment by wcyy** [comment]
> 不管用，。。我双击运行安装组件，。直接给我闪退了，生成蒙版时。同样报错。你说的文件我放了。没起作用

已经解决了。
