### ISSUE TITLE
ControlNet URL Is Not Accessible

### ISSUE THREAD

**Issue by Carzit** [huchang47/AetherConverTools#6]
from the cn_url 'http://127.0.0.1:7860/controlnet/control_types', I can only get 
```
{
    "detail": "Not Found"
}
```

so the programme raise error:

```
Traceback (most recent call last):
  File "D:\AI_video_producing\AetherConverTools-workflow\bin\05_BatchImg2Img.py", line 136, in <module>
    control_dict= get_CNmap()
  File "D:\AI_video_producing\AetherConverTools-workflow\bin\05_BatchImg2Img.py", line 24, in get_CNmap
    data=ListCN()["control_types"]
KeyError: 'control_types'
```

Can you help me? QAQ

**Comment by huchang47** [comment]
This is the API interface to get the preprocessor and corresponding model that Contrlnet added in version 1.1.2. Theoretically you can fix this by updating Contrlnet to the latest version.
